name: al_quran
description: "The Holy Al Quran"
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shimmer: ^3.0.0
  firebase_core: ^4.2.0
  flutter_riverpod: ^2.6.1
  go_router: ^17.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.5
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  google_sign_in: ^7.2.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

fonts:
  - family: Sogeo
    fonts:
      - asset: fonts/sui.ttf
