// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGbDX1Sv1PCVxr8-k52mnvqRh-FbDIVfk',
    appId: '1:294111292327:web:011c9d4080c7a98be7e482',
    messagingSenderId: '294111292327',
    projectId: 'al-quran-41a02',
    authDomain: 'al-quran-41a02.firebaseapp.com',
    storageBucket: 'al-quran-41a02.firebasestorage.app',
    measurementId: 'G-HFXLTV5GWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu-GH17MaTuI8qg_qbPCGuabj1Pn8dg-0',
    appId: '1:294111292327:android:7f009b1ea4eff0dee7e482',
    messagingSenderId: '294111292327',
    projectId: 'al-quran-41a02',
    storageBucket: 'al-quran-41a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1YpDhsaz0B6JKoUTJuYc4ZxtNV2cuIzk',
    appId: '1:294111292327:ios:d6778705b6ecab01e7e482',
    messagingSenderId: '294111292327',
    projectId: 'al-quran-41a02',
    storageBucket: 'al-quran-41a02.firebasestorage.app',
    iosBundleId: 'com.centrexsoft.alQuran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1YpDhsaz0B6JKoUTJuYc4ZxtNV2cuIzk',
    appId: '1:294111292327:ios:d6778705b6ecab01e7e482',
    messagingSenderId: '294111292327',
    projectId: 'al-quran-41a02',
    storageBucket: 'al-quran-41a02.firebasestorage.app',
    iosBundleId: 'com.centrexsoft.alQuran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGbDX1Sv1PCVxr8-k52mnvqRh-FbDIVfk',
    appId: '1:294111292327:web:32b9c7265d151e99e7e482',
    messagingSenderId: '294111292327',
    projectId: 'al-quran-41a02',
    authDomain: 'al-quran-41a02.firebaseapp.com',
    storageBucket: 'al-quran-41a02.firebasestorage.app',
    measurementId: 'G-F8HW3ZS6W1',
  );
}
